=== AlsoSteffen/steffen-visualizer/schema/tweets/tweets_schema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           elementFormDefault="qualified"
           xmlns="https://www.w3schools.com">

    <xs:element name="tweets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tweet" type="Tweet" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Tweet">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="link" type="xs:string"/>
            <xs:element name="content" type="xs:string"/>
            <xs:element name="date" type="xs:long"/>
            <xs:element name="retweets" type="xs:int"/>
            <xs:element name="favorites" type="xs:int"/>
            <xs:element name="mentions" type="xs:string"/>
            <xs:element name="tags" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>



</xs:schema>

=== AlsoSteffen/steffen-visualizer/schema/tweets/tweets_test.xml
<?xml version='1.0' encoding='utf-8'?>
<tweets   xmlns="https://www.w3schools.com"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="https://www.w3schools.com tweets_schema.xsd">
    <tweet>
        <id>81145628</id>
        <link>test</link>
        <content>test</content>
        <date>415151531</date>
        <retweets>131</retweets>
        <favorites>2515</favorites>
        <mentions>1214956456</mentions>
        <tags>test</tags>
    </tweet>

</tweets>
