=== AlsoSteffen/steffen-visualizer/schema/tesla/tesla_schema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           elementFormDefault="qualified"
           xmlns="https://www.w3schools.com">

    <xs:element name="teslaStocks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="teslaStock" type="TeslaStock" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TeslaStock">
        <xs:sequence>
            <xs:element name="date" type="xs:long"/>
            <xs:element name="open" type="xs:double"/>
            <xs:element name="high" type="xs:double"/>
            <xs:element name="low" type="xs:double"/>
            <xs:element name="close" type="xs:double"/>
            <xs:element name="volume" type="xs:double"/>
            <xs:element name="adjClose" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== AlsoSteffen/steffen-visualizer/schema/tesla/tesla_test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<teslaStocks xmlns="https://www.w3schools.com"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://www.w3schools.com tesla_schema.xsd">

    <teslaStock>
        <date>1286661600000</date>
        <open>1.0</open>
        <high>2.0</high>
        <low>3.0</low>
        <close>4.0</close>
        <volume>5</volume>
        <adjClose>6.0</adjClose>
    </teslaStock>

</teslaStocks>
